from pathlib import Path

REPO_DIR = Path(__file__).parent.parent


def _get_version():
    # from https://smarie.github.io/python-getversion/#package-versioning-best-practices
    # and setuptools_scm docs
    try:
        # import from _version.py generated by setuptools_scm during release
        from ._version import version

        return version
    except ImportError:
        from importlib.metadata import version, PackageNotFoundError

        try:
            return version("rapid-clay-formations-fab")
        except PackageNotFoundError:
            # package is not installed
            pass

    return "src"


__version__ = _get_version()
